# Generated by Django 3.0 on 2019-12-11 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myForum', '0003_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 12, 11, 7, 13, 38, 608303, tzinfo=utc))),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection', to='myForum.SubSection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
