# Generated by Django 3.0 on 2019-12-17 03:24

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 3, 24, 48, 56501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 3, 24, 48, 56518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 3, 24, 48, 55975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 3, 24, 48, 55996, tzinfo=utc)),
        ),
    ]
